apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-08-07T18:08:26Z"
  generation: 1
  labels:
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: configuration-service
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/version: 0.7.0
    helm.sh/chart: control-plane-0.7.0
  name: configuration-service
  namespace: keptn
  resourceVersion: "9895678"
  selfLink: /apis/apps/v1/namespaces/keptn/deployments/configuration-service
  uid: b6e03bd1-3ef0-416d-b19d-368e4070640b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: keptn
      app.kubernetes.io/name: configuration-service
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: control-plane
        app.kubernetes.io/instance: keptn
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: configuration-service
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/version: 0.7.0
        helm.sh/chart: control-plane-0.7.0
    spec:
      containers:
      - env:
        - name: MONGODB_HOST
          value: mongodb:27017
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: mongodb-credentials
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mongodb-credentials
        - name: MONGO_DB_NAME
          value: keptn
        image: docker.io/keptn/configuration-service:0.7.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 10999
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: configuration-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        #volumeMounts:
        #- mountPath: /data/config
        #  name: configuration-volume
      - env:
        - name: PUBSUB_URL
          value: nats://keptn-nats-cluster
        - name: PUBSUB_TOPIC
          value: sh.keptn.>
        - name: PUBSUB_RECIPIENT
          value: 127.0.0.1
        - name: PUBSUB_RECIPIENT_PATH
          value: /v1/event
        image: docker.io/keptn/distributor:0.7.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 10999
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: distributor
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: keptn-configuration-service
      serviceAccountName: keptn-configuration-service
      terminationGracePeriodSeconds: 30
      #volumes:
      #- name: configuration-volume
      #  persistentVolumeClaim:
      #    claimName: configuration-volume
status:
  conditions:
  - lastTransitionTime: "2020-08-07T18:08:35Z"
    lastUpdateTime: "2020-08-07T18:08:35Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2020-08-07T18:08:35Z"
    lastUpdateTime: "2020-08-07T18:11:33Z"
    message: ReplicaSet "configuration-service-66f59c65f9" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
