apiVersion: v1
kind: Pod
metadata:
  name: my-mongo-client
  namespace: mongodb
spec:
  containers:
  - name: my-mongo-client
    image: mongo:4.4.0
    command: ["tail", "-f", "/dev/null"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
