apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    creationTimestamp: "2020-08-07T07:37:14Z"
    name: non-dynamic
    resourceVersion: "9403218"
    selfLink: /apis/storage.k8s.io/v1/storageclasses/non-dynamic
    uid: e84e9465-0aa6-4333-9959-408ee95dcd5e
  provisioner: no-provisioning
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
